### DISCUSSION TITLE
Curly brackets in YAMLs

### DISCUSSION THREAD

**Discussion by chosey85** [zed-industries/zed#10250] [Feature Requests]
Hi,

Wondering if it might be a configuration issue from my end or a bug.

When working on YAML files and using curly brackets, when I save my file, Zed adds spaces between the curly brackets to the text inside.
For example:
before save: {text}
after save: { text }

Has anyone experienced this and know how to solve?

Thanks,

**Comment by hustic** [comment]
Faced the same issue when wanting to use Jinja Macros. This is due to the default prettier config (setting `bracketSpacing`). 
I resolved it with `language_overrides` :
```json
"language_overrides": {
    "YAML": {
      "prettier": {
        "bracketSpacing": false
      }
   }
}
```

**Reply by alperdedeoglu** [reply]
Having same issue with templates in Helm Charts, where did you put this config may I ask?

**Reply by hustic** [reply]
In in the `settings.json`. I believe you can open it by: `Zed` -> `Settings...` -> `Open Settings`.
And then you either append an entry in the json, or populate the empty curlys, like so:
```
{
  "languages": {
    "YAML": {
      "prettier": {
        "bracketSpacing": false
      }
    }
}
```

**Reply by thuibr** [reply]
This doesn't work for me. Do I need to restart zed or something? I still get `{ { something } }`.

**Comment by mrkbs** [comment]
If you are using the `yaml-language-server` this is how you can disable the bracket spacing in your `settings.json`.

```yaml
"lsp": {
    "yaml-language-server": {
      "settings": {
        "yaml": {
          "format": {
            "bracketSpacing": false
          }
        }
      }
    }
  }
```
