### DISCUSSION TITLE
Use emmet snippets in JSX.

### DISCUSSION THREAD

**Discussion by diwasrimal** [zed-industries/zed#11812] [Feature Requests]
Why are emmet snippets not working with JSX syntax?

**Comment by nstlgy** [comment]
that feature is still under development, you can follow the issue here #5267

**Comment by d1y** [comment]
Workaround: edit `~/Library/Application\ Support/Zed/extensions/installed/emmet/extension.toml` add js && ts language support

```toml
[language_servers.emmet-language-server]
language = "HTML"
# add JavaScript && TypeScript
languages = ["HTML", "PHP", "ERB", "JavaScript", "TypeScript"]

[language_servers.emmet-language-server.language_ids]
# JavaScript = "javascriptreact"
# TypeScript = "typescriptreact"
```

<img width="974" alt="image" src="https://github.com/zed-industries/zed/assets/45585937/7d4e74e2-3536-43ad-8613-36c184911b19">
