### DISCUSSION TITLE
Trying to implement syntax highlighting using Zed Extensions

### DISCUSSION THREAD

**Discussion by Belluxx** [zed-industries/zed#14671] [Feature Requests]
This is my extension structure
```
smali
  ├── languages
  │   └── smali
  │       └── config.toml
  └── extension.toml
```

This is extension.toml
```toml
id = "smali"
name = "Smali"
version = "0.1"
schema_version = 1
authors = ["User <user@example.com>"]
description = "Smali syntax highlighting"
repository = "https://github.com/repo"

[grammars.smali]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-smali"
commit = "fdfa6a1febc43c7467aa7e937b87b607956f2346"
```

This is config.toml
```toml
name = "Smali"
grammar = "smali"
path_suffixes = ["smali"]
```

However syntax highlighting is not working at all. What should i do?
