### DISCUSSION TITLE
Instructions to add a new language unclear

### DISCUSSION THREAD

**Discussion by St0wy** [zed-industries/zed#14672] [Feature Requests]
I'm trying to add syntax highlighting for Jai, to do this I forked a tree sitter grammer so that it could compile with Zed (https://github.com/St0wy/tree-sitter-jai) and created a local folder with the extension.

My `extension.toml` looks like :
```toml
id = "jai"
name = "Jai"
# other stuff...

[grammars.jai]
repository = "https://github.com/St0wy/tree-sitter-jai"
commit = "4dd73116893b30a4341c62cbcdca51619b34b154"
```

I also added a `languages/jai` with a `highlights.scm` and a `config.toml` that looks like :
```toml
name = "Jai"
grammar = "jai"
path_suffixes = ["jai"]
line_comments = ["// "]
autoclose_before = ";:.,=}])"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "/*", end = " */", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
]
```

But Jai files are still not syntax highlighted and I can't seem to select Jai in the languages menu:

![image](https://github.com/user-attachments/assets/4c3523ff-9f00-4358-ae6e-28be97e6767f)

Is there anything wrong I'm doing ? Do I need to add an LSP for it to work ?

Thanks !

(Edit: I see that someone pretty much asked the same thing for another language at the same time as me, sorry !)
