### DISCUSSION TITLE
Espanso compatibility tip

### DISCUSSION THREAD

**Discussion by AndydeCleyre** [zed-industries/zed#15869] [Show and tell]
Hello! I had begun filling out a new issue for compatibility with Espanso (text replacement / snippet expansion tool), but in doing so figured out a good solution, so I'll just share that here instead.

I'm using Linux, X11, and Plasma DE, and found this smooths over Espanso's interaction with Zed.

`~/.config/espanso/config/zed.yml`:

```yaml
filter_class: ^dev\.zed\.Zed$
key_delay: 4
backend: clipboard
```
