### DISCUSSION TITLE
How long does it take for you to build zed-git?

### DISCUSSION THREAD

**Discussion by chenyo-17** [zed-industries/zed#17065] [Feature Requests]
Hi here!

First of all, I really like Zed, especially the feature that all interaction with the assistant is text-based and transparent. I am recently using it as my primary IDE.

There is however a small issue for me whenever there is an update: it takes so long to build zed-git from AUR: almost an hour (See screenshot below).

![image](https://github.com/user-attachments/assets/d8a8940d-17dd-4055-acae-3b137768d315)
![image](https://github.com/user-attachments/assets/fdef7015-d2de-4aca-8e20-39fffe537baf)

In addition, during this process, all my CPU cores are full-loaded, meaning any other operation can make the system hang, so I mostly just wait for it.

It's very true that my laptop is quite outdated (see screenshot below), especially I only have an integrated GPU. So it's not so unsurprising for me to encounter such a performance.

![system-info](https://github.com/user-attachments/assets/9486fd07-c31b-4931-ba7a-522fbddcf9bf)

I would like to know two things from you:
- What is your "normal" time and load to build zed-git?
- Are there any way one can optimize this process, e.g., modify PKGBUILD?

If you are wondering why I don't use the official installation script or download a binary. It's because when I first tried them I always had the same issue as [this one](https://github.com/zed-industries/zed/issues/14874), even if I have tried downloading different `xdg-desktop-portal` backups. Building the zed-git however did not have this issue.

Thank you in advance for any answer!

**Comment by lexoliu** [comment]
On my M2 Max, it takes 3m 18s:
<img width="682" alt="Screenshot 2025-02-17 at 10 01 08 am" src="https://github.com/user-attachments/assets/b8261dd8-b307-40a4-8621-8e179e929ffb" />

**Comment by niekdomi** [comment]
AMD Ryzen 5 3600 with 16GB RAM -> 4m 33s

**Comment by failable** [comment]
3m Apple M4 Max

**Comment by ghost** [comment]
AMD Ryzen 5 7530U: 8m 54s :skull:

**Comment by thynus** [comment]
My MacBook Air m3 macOS 14.7.7 took
39min. 53sec on battery
25min. 03sec wall power

Is there something wrong?

**Comment by echokrist** [comment]
From this release: [https://github.com/zed-industries/zed/releases/tag/v0.220.5](url)

### Execution Metrics from clean build
| Metric | Time |
| :--- | :--- |
| **Total Runtime** | **156.38s** (~2.60 mins) |
| **User Time** | 814.20s |
| **System Time** | 81.84s |

### Hardware & Environment
* **CPU:** AMD Ryzen 9 7950X3D runs at around 4.9-5.0 GHZ all cores.
* **OS:** CachyOS (Linux) with kernel:l Linux 6.18.7-2-cachyos
* **RAM:** 32GB DDR5 @ 5600MHz
* **SSD:** Corsair MP700 Elite 2TB

---

##  Cargo Configuration
Sharing my own global cargo config.toml.

**File:** `.cargo/config.toml`

```toml
[build]
rustc-wrapper = "sccache"

# --- 1. Ryzen 7950X3D (Linux) Settings ---
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=--ld-path=wild", # High-speed Linux linker
    "-C", "target-cpu=native",      # Uses Zen 4 AVX-512
    "-C", "split-debuginfo=unpacked",
]

[profile.dev]
opt-level = 0
incremental = true
debug = 1 

[profile.dev.package."*"]
opt-level = 1

[profile.release]
opt-level = 3
lto = "thin"          
codegen-units = 32    
panic = "abort"       
strip = "symbols"
```

---
