### DISCUSSION TITLE
Blade support in Emmet extension

### DISCUSSION THREAD

**Discussion by ZayRTun** [zed-industries/zed#18063] [Feature Requests]
Hi, 

I was trying to enable Emmet in laravel blade files but it seems that it's not possible unless Blade is added to Emmet's languages array in the config file.

Kindly advise on how to fix this.

**Comment by notpeter** [comment]
You should be able to clone the [zed repo](https://github.com/zed-industries/zed/) and then open your Extensions panel (cmd-shift-x) and then click "Install Dev Extension" and point it at the [extensions/emmet](https://github.com/zed-industries/zed/tree/main/extensions/emmet) subdirectory of the repo you checked out.

Note you'll need to install (most) of the pre-reqs for building Zed in order to develop extensions.  Instructions are here: [Docs: Developing Zed](https://zed.dev/docs/development).

Once you have successfully installed the unchanged version of the Emmet extension you should be able to edit the extension.toml to add the desired languages:

https://github.com/zed-industries/zed/blob/main/extensions/emmet/extension.toml#L9-L20

Then you can just click "Rebuild Extension" under the extension panel and it will rebuild/reinstall with your changes. More info [Zed Docs: Developing Extensions](https://zed.dev/docs/extensions/developing-extensions).

**Reply by ZayRTun** [reply]
Will give it a try...

**Reply by neurodynamic** [reply]
@ZayRTun Were you able to get this to work? I'm trying to get Emmet to work in .heex/.eex templates using the same technique and I can't seem to get the edited version of the extension to take.

**Reply by kahakai** [reply]
> @ZayRTun Were you able to get this to work? I'm trying to get Emmet to work in .heex/.eex templates using the same technique and I can't seem to get the edited version of the extension to take.

You can open and edit the file `~/Library/Application\ Support/Zed/extensions/installed/emmet/extension.toml` to reference HEEx extension. You don't have to touch or edit anything else in the file. Restart Zed after you made the changes to the file.
I included Elixir extension below too to make Emmet work for function components in `.ex` files inside the `~H` sigil.

```toml
[language_servers.emmet-language-server]
language = "HTML"
languages = ["Elixir", "HEEX"]

[language_servers.emmet-language-server.language_ids]
Elixir = "Elixir"
HEEX = "heex"
```

**Reply by Hbbb** [reply]
Chiming in here. I've been trying to get this to work for a Go templating language called [Templ](https://templ.guide/).

I followed your suggestion to edit the Emmet extension config:
```bash
hx ~/Library/Application\ Support/Zed/extensions/installed/emmet/extension.toml
```

And updated it to include Templ:
```toml
[language_servers.emmet-language-server]
language = "HTML"
languages = ["HTML", "PHP", "ERB", "JavaScript", "TSX", "CSS", "Templ"]

[language_servers.emmet-language-server.language_ids]
TSX = "typescriptreact"
HTML = "html"
PHP = "php"
JavaScript = "javascriptreact"
CSS = "css"
ERB = "eruby"
Templ = "Templ"
```
> I found the Templ "language ID" from it's own extension's TOML [here](https://github.com/makifdb/zed-templ/blob/main/extension.toml)

Has anyone had better luck with this than I have?
