### DISCUSSION TITLE
My first Zed-focused project: MPC servers for everyone

### DISCUSSION THREAD

**Discussion by phil65** [zed-industries/zed#21353] [Show and tell]
If someone wants to have an easy way to set up custom slash commands, I created a MPC server serving content declared in a YAML file.

minimal working example

```yaml
global_settings:
  scripts:
    - "https://gist.githubusercontent.com/phil65/9b57d35ea63f354cf056e0c7d4a62885/raw/d69c01f1bc56a18a1a0e3292a32003f6c4ab6a6f/get_readme.py"

prompts:
  get_readme:
    import_path: get_readme.get_readme
    # name: "Fetch Readme for package"
    description: "Fetch README.md for PyPi package"

```

Start server with this YAML file by putting the start command into Zed settings and you get a new slash command in Zed to quickly get READMEs for external packages. Easy way to let a LLM deal with external unknown packages.
There are probably lot more cool use cases, you can just reference any python function in the YAML.

This also allows declaring tools for LLMs in a super simple way, lookin at the logs they also get registered, but I think Zed is lacking that functionality up to today.

Make sure that all functions are well typed with docstrings etc since the tool uses that information for the mpc part.

https://github.com/phil65/LLMling

Enjoy!
