### DISCUSSION TITLE
Autoclose within single- and doublequotes

### DISCUSSION THREAD

**Discussion by jsf-h** [zed-industries/zed#21823] [Feature Requests]
Hi Folks,

currently it seems not to be possible to use _autoclose_ within quotes.
My usecase would be mainly for writing YAML Files for Ansible ( but maybe there are more usecases)

Currently expressions in YAML like this are tedious to type, because there is no _autoclose_ for any char within the Quotes

Example:

```
---
- name: foobar
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    var_a: "{{ lookup('env', 'SOME_ENV_VAR') }}"
    some_dir: "{{ '~/.config/foo' | bar }}"
```

As you can see this gets quickly out of hand, because within Quotes the _autoclose_ is turned off until you are outside of the Quotes again. 

I think a config option to toggle this behaviour would be very useful, while keeping the current (sane) behaviour the default behaviour. Combined with the per Language Settings a you could easily switch to the new behaviour for cases like YAML

Maybe I am overseeing something and just wanted to ask if I am missing something before opening an Feature Request
In the config options i could not find a setting related to this
