### DISCUSSION TITLE
Connect to Github of Github Copilot is opening vscode

### DISCUSSION THREAD

**Discussion by igotfr** [zed-industries/zed#22315] [Feature Requests]
when I click on Github Copilot icon -> Sign In -> Connect to GitHub, it's opening the vscode and I can't connect to Github Copilot

## System
edora release 40 (Forty)
NAME="Fedora Linux"
VERSION="40 (Workstation Edition)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 40 (Forty)
Fedora release 40 (Forty)

**Comment by notpeter** [comment]
What platform are you on (Linux, macOS, Windows)?  This should be opening a link in the default Web browser -- I wonder if for some reason VSCode is set to the default web handler.

Does Zed open VSCode when you click on a normal URL in terminal (hold command/ctrl when hovering over the link):
```
echo https://zed.dev/docs/
```

**Reply by igotfr** [reply]
I'm using Fedora 40. Yes, it's opening vscode when I click on a link in terminal, how can I change this?

**Reply by igotfr** [reply]
I solve this changing the default browser

`$ vim ~/.local/share/applications/chromium.desktop`
```toml
[Desktop Entry]
Version=1.0
Name=Chromium
Exec=/usr/bin/chromium-browser %U
Terminal=false
Icon=chromium
Type=Application
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/x-mimearchive;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;
```

`$ xdg-settings set default-web-browser chromium.desktop`
