### DISCUSSION TITLE
Logging from extensions?

### DISCUSSION THREAD

**Discussion by dradtke** [zed-industries/zed#23789] [Feature Requests]
I'm able to see Zed's logs at `~/.local/share/zed/logs/Zed.log`, but it doesn't seem to contain logs from any extensions. In particular, I'm trying my hand at developing an extension, and I want to make sure that everything is working correctly.

Here's my sample `Cargo.toml`:

```toml
[package]
name = "my-extension"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.2.0"
log = "0.4.25"
```

and my `src/lib.rs`:

```rust
use zed_extension_api as zed;

struct MyExtension {
    // ... state
}

impl zed::Extension for MyExtension {
    fn new() -> Self {
        println!("[println] Creating extension for MyExtension");
        log::info!("[log] Creating extension for MyExtension");
        Self {}
    }
}

zed::register_extension!(MyExtension);
```

I'm able to install this extension and I can see it in the Extensions page, but I'm not seeing any reference to MyExtension in the logs. Is there another way I should be logging?
