### DISCUSSION TITLE
Conflict Resolution Tool

### DISCUSSION THREAD

**Discussion by JosephTLyons** [zed-industries/zed#26510] [Feature Requests]
Zed should give the user a way to handle conflicts.

- Ability to step through all changes on left and right, and accept either side
- Ability to merge all non-conflicts
- Ability to manually edit the merged code
- Cleanly labeled. I would love to avoid "ours" and "theirs", using SHAs, etc., as this makes it hard if you are handling a conflict between two chunks of code you did not write. Let's just use the commit messages to make it easy to see which side is which.

A bonus would be that you never have to leave your keyboard to handle conflicts.

Related:

- https://github.com/zed-industries/zed/issues/4964

**Comment by SuperKenVery** [comment]
Really missing VSCode's merge editor!

**Comment by JosephTLyons** [comment]
Hey all, initial support for conflict resolution landed in [`v0.185.0-pre`](https://zed.dev/releases/preview/0.185.0) and will be in next stable release (May 7th). The initial version doesn't include all the mentioned features here, but we should open new discussions to track those specific conflict resolution features.

<img width="1496" alt="SCR-20250503-rufo" src="https://github.com/user-attachments/assets/b31df63b-07a7-453e-ac74-115b2b2272b9" />

**Comment by SuperKenVery** [comment]
Any plans for a 3-way diff editor?

**Comment by jasikpark** [comment]
Is there a way to start conflict resolution from the CLI? 

I can set up vscode as a conflict resolution tool for `jj` via:

```toml
[merge-tools.vscode]
program = "code"
merge-args = ["--wait", "--merge", "$left", "$right", "$base", "$output"]
# VS Code reads the output file and behaves better if it's prepopulated with conflict
# markers. Unfortunately, it does not seem to be able to output conflict markers when
# the user only resolves some of the conflicts.
merge-tool-edits-conflict-markers = true
```

While I wait for https://github.com/zed-industries/zed/issues/21538, it'd be great to improve my workflow with zed + jj!
