### DISCUSSION TITLE
Go template language support

### DISCUSSION THREAD

**Discussion by fornellas-maze** [zed-industries/zed#28849] [Feature Requests]
https://pkg.go.dev/text/template

Go templating is fairly common for lots of (infra) tooling. Eg for [tf](https://opentofu.org/):

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
```

AFAIK ATM there's no language support for it, and having to edit such files without syntax highlight is... non optimal.

I reckon templating is tricky for syntax highlight. In this example, it is "sort of a yaml, with sort of bits of go inside", so at least some basic support for what's inside `{{ }}` would be of big aid already.
