### DISCUSSION TITLE
Add proxy server configuration support

### DISCUSSION THREAD

**Discussion by stirelshka8** [zed-industries/zed#30516] [Feature Requests]
**Description:**
Currently, Zed lacks native proxy configuration options, forcing users to rely on system-wide proxy settings or environment variables. This can be problematic in corporate environments where different proxies are needed for different services.

**Requested Feature:**

1. Add proxy configuration options to settings.json:
``` yml
"proxy": {
  "enabled": true,
  "http": "http://proxy.example.com:8080",
  "https": "http://proxy.example.com:8080",
  "no_proxy": "localhost,127.0.0.1,.internal",
  "auth": {
    "username": "optional",
    "password": "optional"
  }
}
```

**2. Support for:**

- Language server connections

- Extension marketplace

- Git operations

- Automatic update checks

**Use Cases:**

- Corporate environments with mandatory proxy usage

- Developers working with remote servers behind proxies
 
- Users who need different proxies for different projects

**Alternatives Currently Available:**

- System proxy settings

- Environment variables (HTTP_PROXY, HTTPS_PROXY)
 
- Manual Git proxy configuration

**Additional Context:**
Many modern editors (VSCode, JetBrains IDEs) provide proxy configuration. This would make Zed more usable in restricted network environments.
