### DISCUSSION TITLE
A setting for which pairs to autoclose

### DISCUSSION THREAD

**Discussion by fdemb** [zed-industries/zed#33077] [Feature Requests]
Hello,
can auto-closing pairs (like [], () etc) be configured so I can choose which pairs I want to autoclose? I'm using Zed to edit Vue.js files and it autocloses "<" and ">" brackets for me, which I don't want. I can disable autoclosing for Vue entirely, but autoclosing for other brackets would be also disabled and I'd prefer to leave them enabled. I couldn't find any key in settings.json to configure individual brackets autoclosing.
Weirdly enough, other file formats like TypeScript, PHP or JSON don't have auto-closing on <> brackets, while Vue does.

**Comment by 0x2CA** [comment]
```json
  // Whether to automatically add matching closing characters when typing
  // opening parenthesis, bracket, brace, single or double quote characters.
  // For example, when you type (, Zed will add a closing ) at the correct position.
  "use_autoclose": true,
  // Whether to automatically surround selected text when typing opening parenthesis,
  // bracket, brace, single or double quote characters.
  // For example, when you select text and type (, Zed will surround the text with ().
  "use_auto_surround": true,
  // Controls how the editor handles the autoclosed characters.
  // When set to `false`(default), skipping over and auto-removing of the closing characters
  // happen only for auto-inserted characters.
  // Otherwise(when `true`), the closing characters are always skipped over and auto-removed
  // no matter how they were inserted.
  "always_treat_brackets_as_autoclosed": false,
```

**Reply by fdemb** [reply]
These settings work globally and disable all autoclosing. I effectively need to specify which pairs I want to autoclose.

**Reply by 0x2CA** [reply]
Currently there is no way to realize individual settings,Because this setting is a language setting

For example, cpp
```toml
name = "C++"
grammar = "cpp"
path_suffixes = ["cc", "hh", "cpp", "h", "hpp", "cxx", "hxx", "c++", "ipp", "inl", "ixx", "cu", "cuh", "C", "H"]
line_comments = ["// ", "/// ", "//! "]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "/*", end = " */", close = true, newline = false, not_in = ["string", "comment"] },
]
debuggers = ["CodeLLDB", "GDB"]
documentation = { start = "/*", end = "*/", prefix = "* ", tab_size = 1 }
```
