### DISCUSSION TITLE
Use StandardRB to Format Ruby Code

### DISCUSSION THREAD

**Discussion by willkoehler** [zed-industries/zed#6560] [Show and tell]
For people that use StandardRB (https://github.com/testdouble/standard), here's the configuration I'm using. 

```
"language_overrides": {
    "Ruby": {
        "formatter": {
            "external": {
                "command": "standardrb",
                "arguments": [
                    "--fix",
                    "--stdin",
                    "ignored",
                    "--stderr"
                ]
            }
        }
    }
}
```

Make sure you have `format_on_save` turned on (see caveats below)

```
{
  "format_on_save": "on"
}
```

### A Few Caveats

- **IMPORTANT** *Edit: This is fixed in StandardRB v1.25.1 If you're using an older version you need to...* turn off parallel in .standard.yml (`parallel: false`). This is the default. Just make sure you didn't turn it on at some point. Otherwise StandardRB will run quitely but you won't see the fixes in Zed
    - See https://github.com/testdouble/standard/issues/530
    - And https://github.com/testdouble/standard/issues/536 
- This config runs the version of StandardRB globally available in your path. I don't think it's possible to run using `bundler` because I don't think you can control what path Zed runs commands from (to be fair I'm mostly guessing, based on comments here https://github.com/zed-industries/community/discussions/1017#discussioncomment-5292800)
- This won't lint your code or show you problems as you edit. It only formats your code when you save it. There's more work to be done here (BTW I would be happy to help /cc @JosephTLyons)
- The third argument `ignored` is required by Rubocop as a parameter for `--stdin`. It's supposed to be "...a path, relative to the root of the project. RuboCop will use this path to determine which cops are enabled" But, from what I can tell, this is ignored by StandardRB.

/cc @searls Zed looks really promising. I'm excited to start using it and helping to improve the Ruby experience. Integration with StandardRB was one of the first things on my list.

**Comment by searls** [comment]
Hey @willkoehler, thanks for this. Heads up I just released 1.25.1 which should fix the `parallel` bug such that you don't need to worry about turning it off in `stdin` mode any more

**Reply by willkoehler** [reply]
Yep 🙌 1.25.1 fixes it. I updated the note above ☝️ to indicate this

**Comment by searls** [comment]
By the way, since standard ruby ships with an [LSP server](https://github.com/testdouble/standard#language-server-protocol-support), it'd be neat to see support for it in Zed.  As an example, I [recently published this VS Code extension](https://marketplace.visualstudio.com/items?itemName=testdouble.vscode-standard-ruby) that uses the LSP to avoid shelling out repeatedly for formatting and diagnostics

**Reply by willkoehler** [reply]
I'm using the Standard Ruby VS Code extension with the LSP server. I agree. It's fantastic 🙌 Very fast and well integrated. I would love to help the Zed team build something like this.

I have some capacity coming up and would be happy to put in the work (and, in particular, keep a low profile and stay out of the team's way) if someone on the Zed team (/cc @JosephTLyons) could help point me in the right direction.

**Reply by bjeanes** [reply]
It'd be great to be able to set a custom LSP for a language.

**Comment by vanhecke** [comment]
This doesn't work for me. I'm getting a "failed to format via external command" error from zed. I'm guessing because stderr is not empty?

I put the following in a bash file and call that instead:

```bash
#!/bin/bash
standardrb --fix --stdin ignored --stderr 2>/dev/null
exit 0
```

**Comment by rhatherall** [comment]
I have tried this and also through Solargraph but no matter how I configure this, I get this in the logs:
```
[WARN] timed out waiting for formatting
```

I have tested calling this externally and it takes about 1.5s to spit out the formatted code. I know that isn't the fastest turn around but it doesn't seem entirely unreasonable. What is Zed's timeout for formatting? Is it configurable?

**Reply by askegg** [reply]
Can confirm. This is what I am getting as well.

**Reply by rhatherall** [reply]
After having a little time to dig into this...

It appears to be an issue loading the Ruby dependencies. I couldn't get this config to work so I tried to revert to using LSP/Solargraph for formatting with either Standard or RuboCop. I ran into issues as I did before. Opening the language server logs showed me that it was having difficulty with resolving the right versions of standard* and rubocop* gems.

Zed doesn't appear to use the bundle configuration, which is where it would have found the correctly installed gems. I have my gems installed per project in `.bundle` so I can have different versions. After installing the gems manually with `gem install` the LSP and formatting started to work. Be warned: The versions had to match the versions defined in Gemfile/Gemfile.lock, so this is not a solution if you work on more than one project (who doesn't?!). I think this is the root of any issues I am having with my Ruby projects/tools.

Also, I have seen occasions where Zed failed to attempt loading an LSP for Ruby files. The Solargraph output just wasn't available until I manually called it to restart the LSP.

**Comment by taylorthurlow** [comment]
Thumbs up on this one, it's one of the last remaining things really holding me back from truly giving an attempt at daily driving Zed. Formatting is important but so are the LSP diagnostics so really the path forward is explicit support for the standardrb LSP or generic, configurable LSP support.

EDIT: Standard has recently shipped a Ruby LSP plugin which is intended, in the long term, to replace the built-in Standard LSP, which sounds great. Seems then that the goal should be to make sure that Ruby LSP works as well as possible, including any addons (though I'm not sure how those work, conceptually).

**Comment by himynameisjonas** [comment]
Threw together a standard-RB extension for Zed. It is very barebones, but it works fine for me.
https://github.com/himynameisjonas/zed-standardrb

**Reply by himynameisjonas** [reply]
This is not needed anymore, you can use the built in ruby-lsp extension instead: https://github.com/zed-industries/zed/discussions/6560#discussioncomment-10467489

**Comment by jarednorman** [comment]
Standard now ships with a ruby-lsp plugin and I can see the language server picking it up in the logs, but so far the formatting isn't working. Trying to work out what's going on with that currently. 

Here's Zed's language server logs:

![CleanShot 2024-07-23 at 16 43 07@2x](https://github.com/user-attachments/assets/f86df150-18f3-4f95-a8ac-8c2d78d19789)

I have the following in my config:

```json
  "languages": {
    "Ruby": {
      "tab_size": 2,
      "language_servers": ["ruby-lsp", "!solargraph", "!rubocop"],
      "formatter": "language_server"
    },
  },
  "lsp": {
    "ruby-lsp": {
      "initialization_options": {
        "enabledFeatures": {
          "diagnostics": false
        }
      }
    }
  }
```

Completion is working, so ruby-lsp is working, but I'm not seeing anything about formatting in here. Anyone have any ideas?

**Reply by jdowd** [reply]
I've done a bunch of mucking around with this and the best results I've gotten have been from @himynameisjonas's extension. Have you tried that? His repo is above and his relevant blog post is https://jonas.brusman.se/zed-and-standard-ruby/

**Reply by jarednorman** [reply]
For the record, here's my config now that I have it working:

```json
  "languages": {
    "Ruby": {
      "tab_size": 2,
      "language_servers": ["ruby-lsp", "!solargraph", "!rubocop"],
      "formatter": "language_server",
      "format_on_save": "on"
    },
  },
  "lsp": {
    "ruby-lsp": {
      "initialization_options": {
        "enabledFeatures": {
          "diagnostics": false,
          "formatting": true
        },
        "formatter": "standard"
      }
    }
  }
```

It turns out that I just needed to enable formatting and specify the formatter.

**Reply by himynameisjonas** [reply]
Nice! I played around with this before building my own extension but never got it to work. Turns out I just had an issue with old gems, after a `gem uninstall prism` followed by a new `gem install ruby-lsp` it all started to work 🚀

**Reply by ascarter** [reply]
Why did you have to uninstall prism? Isn't that part of the default gem set now for Ruby? I can only get `syntax-tree` formatter to work. If I install `standard` and set formatter to it, I don't get any formatting. I assume `syntax-tree` is coming from prism

**Comment by taylorthurlow** [comment]
I have formatting working through Ruby LSP via the standard addon:

```json
    "ruby-lsp": {
      "initialization_options": {
        "experimentalFeaturesEnabled": true,
        "formatter": "standard",
        "linters": ["standard"],
        "enabledFeatures": {
          "codeActions": true,
          "codeLens": true,
          "completion": true,
          "definition": true,
          "diagnostics": false, // until Zed supports pull-type diagnostics
          "documentHighlights": true,
          "documentLink": true,
          "documentSymbols": true,
          "foldingRanges": true,
          "formatting": true,
          "hover": true,
          "inlayHint": true,
          "onTypeFormatting": true,
          "selectionRanges": true,
          "semanticHighlighting": true,
          "signatureHelp": true,
          "typeHierarchy": true,
          "workspaceSymbol": true
        },
        "featuresConfiguration": {
          "inlayHint": {
            "implicitHashValue": true,
            "implicitRescue": true
          }
        }
      }
    },
```

```json
    "Ruby": {
      "tab_size": 2,
      "language_servers": [
        "ruby-lsp",
        "!solargraph",
        "!rubocop",
        "..."
      ]
    }
```

**Reply by searls** [reply]
Nice! Going forward, this is probably the best approach

**Reply by TrevorHinesley** [reply]
Is it possible to set this up to fallback to rubocop if standard isn't available on a project? and/or to fallback to nothing if rubocop isn't either?

**Comment by tttffff** [comment]
For me @jarednorman's suggestion was fine https://github.com/zed-industries/zed/discussions/6560#discussioncomment-10467489. However, it didn't provide the squirly lines when there's an issue, or an explaination on hover, it only fixed (fixable) issues on saving. Not sure if I have done something wrong there.

My solution is to use Solagraph + Rubocop, but to tell Rubocop to use standard's rules. It works nice for me.

You get the green squirly lines, the explaination on hover, and Rubocop also reports other useful things e.g. when you've defined the same method twice in a class.

- No need for the "language_servers" part of the settings as Solargraph and Rubocop are both selected by default by the Ruby extension.
- Add the lsp config to have Solagraph do formatting. See: https://zed.dev/docs/languages/ruby#setting-up-solargraph
- Add a Rubocop config to your project's root.

#### settings.json
```yml
  "lsp": {
    "solargraph": {
      "initialization_options": {
        "diagnostics": true,
        "formatting": true
      }
    }
  }
```
#### .rubocop.yml
```yml
inherit_gem:
  standard: config/base.yml
```

Edit: see https://github.com/standardrb/standard?tab=readme-ov-file#running-standards-rules-via-rubocop for other things you may want in .rubocop.yml

**Reply by taylorthurlow** [reply]
You would need to use StandardRB's built-in LSP to get diagnostics (the squiggly lines), as Zed doesn't currently support "pull type" diagnostics, only "push type", and the ruby-lsp language server only does pull type. It works pretty much the same way the rubocop diagnostics that you're getting through Solargraph, just without the extra indirection of Solargraph.

So this, in addition to the already-configured `ruby-lsp`.
```json
"standardrb": {
  "initialization_options": {
    "enabledFeatures": {
      "diagnostics": true,
      "formatting": false
    }
  }
},
```

```json
"Ruby": {
  "tab_size": 2,
  "language_servers": [
    "ruby-lsp",
    "standardrb",
    "!solargraph",
    "!rubocop",
    "..."
  ]
}
```

**Reply by tttffff** [reply]
Thanks for this! Your approach feels like it makes the most sense.

However, I cannot get it to work. I'm sure it's just a skill/knowledge issue.

When you've mentioned the "standard addon" in your previous comment, are you talking about this: https://github.com/himynameisjonas/zed-standardrb? I tried installing it as a dev extension, but it didn't seem to do anything, then ran `cargo b` in that directory (I've never done any Rust before), it seemed to do things, but still can't get it to install in Zed.

<details>

<summary>The settings that I've tried</summary>

```yml
{
  "ui_font_size": 12,
  "buffer_font_size": 12,
  "buffer_font_family": "JetBrainsMono Nerd Font",
  "font_family": "JetBrainsMono Nerd Font",
  "theme": {
    "mode": "system",
    "light": "One Light",
    "dark": "Catppuccin Mocha"
  },
  "vim_mode": false,
  "language": {
    "Ruby": {
      "language_servers": ["ruby-lsp", "standardrb", "!solargraph", "!rubocop"]
    }
  },
  "lsp": {
    "ruby-lsp": {
      "initialization_options": {
        "experimentalFeaturesEnabled": true,
        "formatter": "standard",
        "linters": ["standard"],
        "enabledFeatures": {
          "codeActions": true,
          "codeLens": true,
          "completion": true,
          "definition": true,
          "diagnostics": false, // until Zed supports pull-type diagnostics
          "documentHighlights": true,
          "documentLink": true,
          "documentSymbols": true,
          "foldingRanges": true,
          "formatting": true,
          "hover": true,
          "inlayHint": true,
          "onTypeFormatting": true,
          "selectionRanges": true,
          "semanticHighlighting": true,
          "signatureHelp": true,
          "typeHierarchy": true,
          "workspaceSymbol": true
        },
        "featuresConfiguration": {
          "inlayHint": {
            "implicitHashValue": true,
            "implicitRescue": true
          }
        }
      }
    },
    "standardrb": {
      "initialization_options": {
        "enabledFeatures": {
          "diagnostics": true,
          "formatting": false // tried with true as well
        }
      }
    }
  }
}
```

</details>

So I guess, either I've not quite got the settings correct, or I do need to install that extension somehow.
