### DISCUSSION TITLE
Writing an extension with tree-sitter grammar in a subdirectory

### DISCUSSION THREAD

**Discussion by Dekker1** [zed-industries/zed#9901] [Feature Requests]
I was hoping to add support to Zed for a language that I help develop. I'm trying to follow the instructions: https://github.com/zed-industries/extensions/blob/main/AUTHORING_EXTENSIONS.md

We already use a tree-sitter grammar in the project, so it seemed a great fit. However, the tree-sitter grammar/package is located in a larger mono-repo, and I'm not sure how to make this work. In this case the repository is https://github.com/shackle-rs/shackle, but the package/grammar is located in `parsers/tree-sitter-minizinc` directory, not at the root of the repository.

This means that the following `extension.toml` does not work:
```toml
[grammars.minizinc]
repository = "https://github.com/shackle-rs/schackle"
commit = "a4b45135832dadb5ae996ef3efc0a5f4d03d16ee"
```

I would have hoped that there is an additional `location` or something key, but I cannot find any documentation for this. Is there an (undocumented) feature that will allow me to make it work?

**Comment by maxdeviant** [comment]
This is supported by the `path` field:

```toml
[grammars.minizinc]
repository = "https://github.com/shackle-rs/schackle"
commit = "a4b45135832dadb5ae996ef3efc0a5f4d03d16ee"
path = "parsers/tree-sitter-minizinc"
```

It was added in https://github.com/zed-industries/zed/pull/9965, so I don't think it's made its way to a released version yet for use with the "Install Dev Extension" functionality (although it will be included in today's Preview release).
