### ISSUE TITLE
Better ToggleComments support for Comment and Doc

### ISSUE THREAD

**Issue by huacnlee** [zed-industries/zed#10113]
### Check for existing issues

- [X] Completed

### Describe the feature

We have `line_comments` in language config.toml.

For example the Rust:

```toml
name = "Rust"
grammar = "rust"
path_suffixes = ["rs"]
line_comments = ["// ", "/// ", "//! "]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<", end = ">", close = false, newline = true, not_in = ["string", "comment"] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "/*", end = " */", close = true, newline = false, not_in = ["string", "comment"] },
]
collapsed_placeholder = " /* ... */ "
```

But by my test, the Toggle Comments command just work for the first item in line_comments.

### If applicable, add mockups / screenshots to help present your vision of the feature

![2024-04-03 18 32 08](https://github.com/zed-industries/zed/assets/5518/50f7a9cf-6d23-4a9b-900b-548a3bbe70a6)

As shown in the screen recording, if ToggleComments can correctly handle Rust's `///` and `//!`, it will be more convenient for us to write documents. 

For example, many times we need to write a large section of Rust code example. So we many write the code first, and then add `///` prefix to them. If the ToggleComments can handle that, we can just select the all new addition code and run ToggleComments to add the prefix.
