### ISSUE TITLE
Comments in JSON files

### ISSUE THREAD

**Issue by luckydye** [zed-industries/zed#10921]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It seems all files in zed are interpreted to be jsonc (?) and does not have a "JSONC" language.

There are some files in the zed codebase (_assets/keymaps/vim.json_) for example, that use comments in _.json_ files, but langauge-servers don't know about that. So the biome extension for example, shows diagnostics as if they are json files, which doesn't allow comments.

<img width="513" alt="image" src="https://github.com/zed-industries/zed/assets/10381895/3c2fae68-868a-4cfe-b885-e511599b5963">

https://github.com/biomejs/biome-zed/issues/11

### Environment

Zed: v0.132.2 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

**Comment by maxdeviant** [comment]
Would it work to map the `JSON` language to `jsonc` on the Biome extension side?

```toml
[language_servers.biome]
name = "Biome Language Server"
language = "JavaScript"
languages = ["JavaScript", "JSX", "TypeScript", "TSX", "Vue.js", "Astro", "Svelte", "JSON", "JSONC"]
# Map the "JSON" language in Zed to "jsonc" (or whatever ID Biome uses for JSONC files).
language_ids = { JSON = "jsonc" }
code_actions_kind = ["", "quickfix"]
```
