### ISSUE TITLE
Unable to uncomment in embeddings language (injections.scm)

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#11455]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I forked a zed source code myself and picked up #9082
But I found that it was not like before
Although it worked, I couldn't uncomment it(`editor::ToggleComments`)

https://github.com/zed-industries/zed/assets/45585937/3c604241-fc22-465f-bd8e-44db0ed83486

I'm not sure what happened to it, but I'm trying to workaround it

```toml
name = "Comment"
grammar = "comment"
path_suffixes = []
# d1y: 这里如果不标记的话就取消不了注释, 因为注释之后它的语言类型就为 comment 了(maybe?)
line_comments = ["//", "# ", ";;", "--", "%"]
# block_comment = ["/* ", " */"]
brackets = [
  { start = "(", end = ")", close = true, newline = false }
]
```

Subsequent behavior

https://github.com/zed-industries/zed/assets/45585937/a030bbd9-f9f8-440f-9f0f-e2eba271a48d

Fork commit here: https://github.com/d1y/zed/commit/4ee1c45756eacdb2621a0d2b9190c0c9771d002c

I know this may be a bit out of line, but I want to report this matter /cc @maxbrunsfeld @maxdeviant 

> Will subsequent extensions also have this problem if they are injected into the language?

### Environment

Fork main local build version
