### ISSUE TITLE
Disable auto indent while maintaining indent level in new lines

### ISSUE THREAD

**Issue by YotGun** [zed-industries/zed#11780]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently AFAIK it is impossible to disable auto indentation in Zed. This is very annoying to deal with especially in Python as mentioned in #10832. This feature should be toggle-able or be more customizable. I do not want code I write to magically jump after typing a colon after I already decided at its location. This should make it more consistent with the customizability in VScode.

Example:
What happens when I create a new line:

Current:
`....if x:
........| # Where line starts`

Proposed setting:
`....if x:
....| # Where line starts`

**Comment by jeromechoo** [comment]
This is absolutely critical for Python. But even for other languages I can't use Zed if I'm pulling an existing project that uses a certain style of indentation that I'm trying to follow.

**Comment by salzig** [comment]
Besides being annoying, it also generates wrong results

given the following yaml (gitlab-ci.yml example):
```
test:
  script:
    - ./gradlew test
```

if I go to a new empty line after the script section and want to paste the following
```
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/TEST-*.xml
 ```
 
it tries to be clever and produces this:
```
test:
  script:
    - ./gradlew test
    artifacts:
      when: always
      reports:
        junit: build/test-results/test/TEST-*.xml
```

instead of the expected:
```
test:
  script:
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/TEST-*.xml
```

but also if I use the following (same text content, but no already indented)
```
artifacts:
  when: always
  reports:
    junit: build/test-results/test/TEST-*.xml
```

it produces the same unexpected/wrong results.

That's not the only situation where the indentation behaviour produces bad results. Just an example on hand. 


I don't mind problems auto indenting, but I do mind not being able to disable it all together.
