### ISSUE TITLE
Multiple documents in one yaml file

### ISSUE THREAD

**Issue by wisniew** [zed-industries/zed#12122]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Having multiple yaml documents in one file, Zed marks the second document all in red with the information:

Source contains multiple documents; please use YAML.parseAllDocuments() at line 169, column 1: (MULTIPLE_DOCS)

Example of yaml file:
``` yaml
metadata:
  name: doc1
---
metadata:
  name: doc2
---
metadata:
  name: doc3
```

aur/zed-editor 0.135.2-1 on Arch Linux 

### Environment

Zed: v1.0.0 (Zed)
OS: Linux 1.0.0
Memory: 13.7 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/18087956/ed3f62bb-d632-4a20-8c22-0ade7f027792)

**Comment by MrHaroldA** [comment]
This makes working with Kubernetes yaml files pretty difficult ...

**Comment by ziermmar** [comment]
Failing Syntax Highlighting for multiple Yaml documents in one file is also occurring in the mac version, 0.145.1 in my case.

**Comment by yodatak** [comment]
I have this issue too with flux2 yaml file

**Comment by yodatak** [comment]
Maybe its upstream ? 
https://github.com/redhat-developer/yaml-language-server/issues/869
https://github.com/redhat-developer/yaml-language-server/issues/946

**Comment by yodatak** [comment]
Not sure to understand but it seem to detect if file is yml or yaml and kubernetes and parse it differently 
https://github.com/redhat-developer/yaml-language-server/blob/f039273ee5b6974db5ad34b03bb24cfe09b64447/src/languageservice/parser/isKubernetes.ts

The multi document yaml test
https://github.com/redhat-developer/yaml-language-server/blob/f039273ee5b6974db5ad34b03bb24cfe09b64447/test/multipleDocuments.test.ts

**Comment by h3adex** [comment]
Bump. Would be nice this fix this issue, since this makes working on kubernetes ressources diffcult.

**Comment by h3adex** [comment]
This bug seems fixed.

**Comment by simonccc** [comment]
I'm still observing this problem on mac Zed 0.149.5

**Comment by imleafz** [comment]
> I'm still observing this problem on mac Zed 0.149.5

me too.

**Comment by weirdo-adam** [comment]
I'm still observing this problem on mac Zed Preview 0.153.1

**Comment by akashsokik** [comment]
same here, still observing this problem, is there a fix for this?

**Comment by weirdo-adam** [comment]
我仍然在 Mac Zed Preview 0.157.4 上观察到这个问题，有解决办法吗？

**Comment by reider-dev** [comment]
Also observed here.

Zed: v0.160.2 (Zed Preview)
OS: Linux Wayland fedora 41
Memory: 62.4 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3080 Ti Laptop GPU || NVIDIA || 560.35.03

**Comment by eth0net** [comment]
Still seeing this issue in today's update, not sure if the bug went away and came back or if h3adex got lucky ^^ 

Zed: v0.163.2 (Zed Preview)
OS: macOS 15.2.0
Memory: 36 GiB
Architecture: aarch64

**Comment by blackmou5e** [comment]
Issue still present.
Zed: v0.166.1

**Comment by notpeter** [comment]
> this is very annoying any ideas what is the underlying problem?

[zed-industries/tree-sitter-yaml](https://github.com/zed-industries/tree-sitter-yaml) properly supports syntax highlighting of multiple documents:

<img width="301" alt="Screenshot 2025-01-01 at 10 13 02" src="https://github.com/user-attachments/assets/7cc46da9-f069-4eda-8136-35d785f21e2a" />

---

I believe the original reported issue may have been solved (all multi-doc yaml files trigger errors) and now it's a kubernetes yaml file specific issue (kubernetes multi-doc yaml files trigger errors) upstream with [redhat-developer/yaml-language-server](https://github.com/redhat-developer/yaml-language-server), perhaps:

- https://github.com/redhat-developer/yaml-language-server/issues/869
- https://github.com/redhat-developer/yaml-language-server/issues/946

If you are still experiencing this issue, could you please comment with a minimal `yaml` file which triggers the issue?  Given that I believe this is a yaml-language-server issue I would expect that vscode with the [redhat.vscode-yaml](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) extension would show identical behavior.

As a (sad) workaround you can disable `yaml-language-server` altogether with the following in your settings:
```json
  "languages": {
    "YAML": {
      "enable_language_server": false
    }
  }
```

**Comment by 1hachem** [comment]
using `Zed 0.166.2` on Arch `6.12.7-arch1-1`

Here is a sample file  

`test.yaml`
```yaml
---
person:
  name: John Doe
  age: 30
  occupation: Software Engineer
  skills:
    - Python
    - JavaScript
    - YAML
---
server:
  host: example.com
  port: 8080
  maintenance_mode: false
  features:
    - API
    - WebSockets
    - Static Content
```

![image](https://github.com/user-attachments/assets/1b88e16f-cc35-4d0a-b9a8-0896ff9d2efa)

**Comment by notpeter** [comment]
@1hachem When I create this as `test.yaml` I don't see the schema errors.  I assume because your pathing is triggering one of the built-in schema association -- can you share your pathing and the associated schema url so we can add a inline schema directive an create a fully self-contained reproduction example?

```
# yaml-language-server: $schema=https://my.url.to/the/schema 
```

Thanks

**Comment by wazoo** [comment]
Okay I can't explain it but I am running into this bug and it does not impact every file and I haven't been able to figure out a commonality.  I am running into it when writing Kubernetes manifests and it is only showing the error on the second document in **some** files.  It doesn't seem to be related to the detected schema, it does it with or without it defined.

Here is an example:

```yaml
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.31.5/namespace-v1.json
apiVersion: v1
kind: Namespace
metadata:
  name: config
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.31.5/namespace-v1.json
apiVersion: v1
kind: Namespace
metadata:
  name: system
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.31.5/namespace-v1.json
apiVersion: v1
kind: Namespace
metadata:
  name: network
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
```

<img width="513" alt="Image" src="https://github.com/user-attachments/assets/e02d98b9-17c4-45b1-8004-56ef2b51767f" />

It seems to do this no matter what the file is named (or if it uses yaml or yml) or how it was created.  I can work around it by leaving an empty document in the second position but it still causes the file tree to show an error on the file.

```
Zed 0.169.2
MacOS 15.2 (24C101)
Apple M2
16GB Memory
```

Let me know if there is any other information that would be helpful!
