### ISSUE TITLE
Pass on jupyter location

### ISSUE THREAD

**Issue by cvanelteren** [zed-industries/zed#15387]
### Check for existing issues

- [X] Completed

### Describe the feature

As it says on the tin. Continuing on https://github.com/zed-industries/zed/issues/5273#issuecomment-2254638397, I would like to add a parameter to point to jupyter that are part of particular envs; virtual envs on unix are a common way to shield from interfering with system python. It is currently unclear how Zed picks up jupyter,  but it seems to look in specific directories. Allowing the user to set that directory would improve the user experience.

**Comment by gRox167** [comment]
I also meet this issue. I install my venv with rye in which I install the jupyter and ipykernel. However, seems that zed could not pick up the location of ipykernel and jupyter. REPL feature is not working because of this.

**Comment by cvanelteren** [comment]
Any movement on this?

**Comment by cvanelteren** [comment]
Ah following the link listed above I was able to use my env
I put a pyproject.toml in my root folder of the project with my env and after a restart it recognized my env

```toml 
#pyproject.toml in root
[tool.pyright]
venvPath = "/home/casper/micromamba/envs"
venv = "/home/casper/micromamba/envs/boiler"

```
