### ISSUE TITLE
Bad kerning in integrated terminal

### ISSUE THREAD

**Issue by lixiaoyan** [zed-industries/zed#16869]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="317" alt="image" src="https://github.com/user-attachments/assets/cb535dbc-8ff6-40c6-ab28-350006e56ed1">

⬆️ Vanilla Alacritty
⬇️ Integrated terminal in Zed

Zed config:
```json
{
  "buffer_font_family": "Iosevka Fixed",
  "buffer_font_size": 11
}
```

Alacritty config:
```toml
[font]
normal = { family = "Iosevka Fixed" }
size = 11
```

### Environment

Zed: v0.149.5 (Zed)
OS: macOS 13.6.9
Memory: 32 GiB
Architecture: x86_64
