### ISSUE TITLE
Project manager / recent projects window

### ISSUE THREAD

**Issue by paderick** [zed-industries/zed#16999]
### Check for existing issues

- [X] Completed

### Describe the feature

When zed 
- was opened the first time
- was closed without a project opened
- opens a new window 
a project manager / recent projects view / window should be shown as it is implemented in IDEs from JetBrains / Apples Xcode or VS Code solve it with the welcome page. 

### If applicable, add mockups / screenshots to help present your vision of the feature

![grafik](https://github.com/user-attachments/assets/1ad617a5-ca36-4302-a11f-9453953e7261)

![grafik](https://github.com/user-attachments/assets/ab39069a-ea12-4f71-b530-302f74023846)

![grafik](https://github.com/user-attachments/assets/1f2bee07-755b-432e-bc87-aa0e212b825c)

**Comment by arv-anshul** [comment]
A feature like viewing all the git initiated project is much needed too. See [VSCode extension](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager) for that.

![image](https://github.com/user-attachments/assets/2d97bb25-a20b-47f1-bee3-2174fbcd6f85)

![image](https://github.com/alefragnani/vscode-project-manager/raw/master/images/project-manager-list-sort-by-name.png)

**Comment by olrtg** [comment]
Doesn't "File -> Open Recent... (⌥⌘O)" does this already? 🤔

**Comment by arv-anshul** [comment]
> Doesn't "File -> Open Recent... (⌥⌘O)" does this already? 🤔

Yes, but it is not what I need. It has only recently opened projects; what about un-opened project or new projects, I want those too.

**Comment by paderick** [comment]
My intention here was to give you feedback what I miss when I come from other tools. It is totally fine to me when you want in your app a behaviour like textedit, which opens a new empty file at startup. 

I expect for a next-generation code editor at startup an "welcome page" which offers my last projects or the option to start a new one.

**Comment by mangas** [comment]
Any thoughts on whether something similar to projectile(for those not familiar, it finds vcs roots under a specific folder and adds them as "projects" that could then be open) would be accepted as a PR for the main editor codebase? As far as I can tell this is currently not possible to implement with the existing WIT interface. 

As far as I can tell for extension it's missing: 
- interface add new commands from extensions
- interface to cache the results (possibly optional, ideally not) 
- interface to open new projects from extension

Adding this natively seems a lot easier to implement, is there a reason why it would not be accepted there?

**Comment by duongquoctue** [comment]
do you guys know whether if Zed has this feature as Extension already?

**Comment by olrtg** [comment]
@duongquoctue it doesn't exist yet. We don't have an API to make that kind of extensions for now sadly.

**Comment by den-is** [comment]
I miss this functionality too.
I'm tightly bound to VSCodes Project Manager extension - to organize my work across multitude of projects.
While of course I can remember and open dirs and projects "manually" - Project Manager Extension provides a slim side panel with a nice list of all projects, I have opened or not - but saved in the list.

**Comment by nihalxkumar** [comment]
@miguelraz perhaps, this can be closed

**Comment by rgebee** [comment]
I would also like project manager functionality in zed. As mentioned by @den-is with recent projects you need to first open the project manually instead of zed automatically detecting and listing all projects for you.

**Comment by MushuPlatypus** [comment]
A feature / extension like the Project Manager from VS Code is what is one of the reaons preventing me from switching to Zed.  Having an easy way to navigate between 20+ projects, is essential for my work flow.

**Comment by nikaro** [comment]
My use of Project Manager was to configure it to point at `~/Developer` to look for all Git projects, so that when i clone a new one (using [git-get](https://github.com/grdl/git-get)) it is right away available (after a projects refresh) without having to navigate through the filesystem to open it.

In the meantime i use this task with a keybinding:
```yaml
  {
    "label": "Project Finder",
    "command": "set result (tv projects); and test -n \"$result\"; and zed --new $result",
    "reveal_target": "center",
    "hide": "always",
  },
```
With this [television](https://github.com/alexpasmantier/television) config:
```toml
# ~/.config/television/cable/projects.toml
[metadata]
name = "projects"
requirements = ["fd", "git"]
description = "A channel to select from git repositories on your local machine"

[source]
command = "fd --glob .git --hidden --follow --type directory --max-depth 10 --prune ~/Developer/ --exec dirname '{}'"
display = "{regex_extract:.*/Developer/(.*):1}"

[preview]
command = "cd '{}'; git log -n 200 --pretty=medium --all --graph --color"
```

But i would definitely prefer something native to the Zed UI.
