### ISSUE TITLE
`log` does not appear to work in extensions

### ISSUE THREAD

**Issue by valentinegb** [zed-industries/zed#17326]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Adding the `log` crate to an extension's `Cargo.toml` and using its macros appears to result in no output. Here's what I have in `Cargo.toml`, specifically:

```toml
[dependencies]
log = { version = "0.4.16", features = ["kv_unstable_serde", "serde"] }
zed_extension_api = "0.1.0"
```

In `src/lib.rs` I simply used `log::debug!()` in the `Extension::language_server_command()` declaration. I am running Zed with `RUST_LOG=debug` and I can see other debug messages.

### Environment

Zed: v0.151.1 (Zed Preview)
OS: macOS 15.1.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16854307/Zed.log)
</pre></details>
