### ISSUE TITLE
Yaml custom tags, unresolved tags

### ISSUE THREAD

**Issue by elvishp2006** [zed-industries/zed#18013]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I had configured my editor to work with a custom lsp config to yaml files, but it keep saying that my custom tags are Unresolved

### Environment

Zed: v0.153.5 (Zed Preview)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

```json
  "lsp": {
    "yaml-language-server": {
      "initialization_options": {
        "yaml": {
          "customTags": [
            "!And scalar",
            "!And mapping",
            "!And sequence",
            "!If scalar",
            "!If mapping",
            "!If sequence",
            "!Not scalar",
            "!Not mapping",
            "!Not sequence",
            "!Equals scalar",
            "!Equals mapping",
            "!Equals sequence",
            "!Or scalar",
            "!Or mapping",
            "!Or sequence",
            "!FindInMap scalar",
            "!FindInMap mappping",
            "!FindInMap sequence",
            "!Base64 scalar",
            "!Base64 mapping",
            "!Base64 sequence",
            "!Cidr scalar",
            "!Cidr mapping",
            "!Cidr sequence",
            "!Ref scalar",
            "!Ref mapping",
            "!Ref sequence",
            "!Sub scalar",
            "!Sub mapping",
            "!Sub sequence",
            "!GetAtt scalar",
            "!GetAtt mapping",
            "!GetAtt sequence",
            "!GetAZs scalar",
            "!GetAZs mapping",
            "!GetAZs sequence",
            "!ImportValue scalar",
            "!ImportValue mapping",
            "!ImportValue sequence",
            "!Select scalar",
            "!Select mapping",
            "!Select sequence",
            "!Split scalar",
            "!Split mapping",
            "!Split sequence",
            "!Join scalar",
            "!Join mapping",
            "!Join sequence",
            "!Condition scalar",
            "!Condition mapping",
            "!Condition sequence"
          ],
          "schemas": {
            "https://raw.githubusercontent.com/aws/serverless-application-model/main/samtranslator/schema/schema.json": "template.yml"
          }
        }
      }
    }
  }
```
<img width="960" alt="Captura de Tela 2024-09-18 às 12 15 41" src="https://github.com/user-attachments/assets/f40debce-bdb5-4854-a4ec-472dd0ca7a40">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Can you provide an minimal example YAML file so I can see if I can reproduce?

**Comment by elvishp2006** [comment]
> Can you provide an minimal example YAML file so I can see if I can reproduce?

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  api-example: API Example

Parameters:
  Stage:
    Type: String
    Default: development
    AllowedValues:
      - development
      - staging
      - production

Conditions:
  IsProductionStage: !Equals [!Ref Stage, production]

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefaultRouteSettings:
        DetailedMetricsEnabled: true
      Domain:
        CertificateArn: arn:aws:acm:us-east-1:000000000000:certificate/be8e5595-4771-4408-9ec2-547a2230bdfds
        DomainName: !Ref DomainName
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: Z1OLBJHSKHIU98

```
