### ISSUE TITLE
Run workflows only in the main repository not on forks

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#19351]
### Check for existing issues

- [X] Completed

### Describe the feature

I forked the latest version recently, but I noticed that the workflows are executed, since I receive that the workflows some are failed, wouldn't it be better not to execute the workflows if we are not in the main repository?

Here are the ones that have been started:

- Bump collab-staging Tag
- CI
- Deploy Docs
- Docs
- Release Nightly
- Update All Top Ranking Issues
- Update Weekly Top Ranking Issues

```yaml
name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    if: github.repository == 'zed-industries/zed'
    runs-on: ubuntu-latest
...
```
