### ISSUE TITLE
Mypy via pylsp seems to be enabled/disabled when the selected venv is changed

### ISSUE THREAD

**Issue by taranlu-houzz** [zed-industries/zed#21181]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am trying to get Zed configured to do the following:
- Use only `ruff` and `mypy` for linting/formatting
- Disable all other type checkers/linters
- Use only the config in my project's `pyproject.toml` (as much as is possible)
- `mypy` and `ruff` are installed externally via `uv tool install`, although I am using the `ruff` extension for `zed`, so I assume that probably uses a bundled version

I think I was finally able to get this config working, but I have found that if I change the venv the editor is set to use to be the one for the project, it causes the `mypy` errors to disappear (I assume this is likely because `mypy` is not installed in the project venv directly). For some reason, when it is set to some other random Python, such as the macOS default system one, the `mypy` errors show up as expected.

One other thing that I noticed (unsure if this is related): somehow, even if the Python interpreter is set to one unrelated to my project, `zed` is still able to give me popup info on function help/docstrings from other modules in my project source. Coming from VSCode, this seems weird, since I would typically need to have set the interpreter to be one where my project was installed in order to get such info.

### Environment

Zed: v0.162.5 (Zed)
OS: macOS 14.7.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

`zed settings`:
```json
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run `zed: open default settings` from the
// command palette (cmd-shift-p / ctrl-shift-p)
{
  "assistant": {
    "default_model": {
      "provider": "copilot_chat",
      "model": "gpt-4o"
    },
    "version": "2"
  },
  "active_pane_modifiers": {
    "magnification": 1.0,
    "border_size": 2.0,
    "inactive_opacity": 0.75
  },
  "pane_split_direction_horizontal": "down",
  "pane_split_direction_vertical": "right",
  "indent_guides": {
    "active_line_width": 2,
    "coloring": "indent_aware",
    "background_coloring": "disabled"
  },
  "vertical_scroll_margin": 0,
  "vim_mode": true,
  "terminal": {
    "shell": {
      "program": "fish"
    },
    "detect_venv": "off"
  },
  "tab_bar": {
    "show_nav_history_buttons": false
  },
  "tabs": {
    "file_icons": true
  },
  "preferred_line_length": 100,
  "ui_font_size": 16,
  "buffer_font_size": 14,
  "theme": {
    "mode": "system",
    "light": "One Light",
    "dark": "Github Dark"
  },
  "lsp": {
    "pylsp": {
      "settings": {
        "plugins": {
          "mypy": {
            "enabled": true
          },
          "pycodestyle": {
            "enabled": false
          }
        }
      }
    }
  },
  "languages": {
    "Python": {
      "language_servers": ["!pyright", "ruff", "pylsp"],
      "format_on_save": "on",
      "formatter": [
        {
          "code_actions": {
            "source.organizeImports.ruff": true,
            "source.fixAll.ruff": true
          }
        },
        {
          "language_server": {
            "name": "ruff"
          }
        }
      ]
    }
  }
}
```
`pyproject.toml`:
```toml
####################################################################################################
# Project
####################################################################################################

[project]
authors = [{ name = "----", email = "----" }]
dependencies = [
    "aiofiles>=24.1.0",
    "beartype>=0.19.0",
    "bidict>=0.23.1",
    "dateparser>=1.2.0",
    "dynaconf>=3.2.6",
    "fastapi>=0.115.5",
    "orjson>=3.10.11",
    "p4python>=2024.2.2682690",
    "pydantic>=2.10.1",
    "rich>=13.9.4",
    "typer>=0.13.1",
    "uvicorn[standard]>=0.32.1",
]
description = "----"
name = "----"
readme = "README.md"
requires-python = ">=3.13,<3.14"
version = "1.0.0a0"

[project.scripts]
pipeline3d-server = "----:run_app"

[build-system]
build-backend = "pdm.backend"
requires = ["pdm-backend"]

####################################################################################################
# UV
####################################################################################################

[tool.uv]
dev-dependencies = [
    "types-aiofiles>=24.1.0.20240626",
    "types-dateparser>=1.2.0.20240420",
]

####################################################################################################
# PDM
####################################################################################################

[tool.pdm]
distribution = true

[tool.pdm.build]
includes = ["src/----"]

[tool.pdm.scripts]
pre_build = "python ../__scripts__/write_metadata.py"

####################################################################################################
# Ruff
####################################################################################################

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
ignore = [
    "B008", # do not perform function calls in argument defaults
    "C901", # too complex
    "E501", # line too long, handled by black
]
preview = true
select = [
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "D",    # pydocstyle
    "DOC",  # pydoclint
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "FAST", # fastapi
    "FLY",  # flynt
    "FURB", # refurb
    "I",    # isort
    "N",    # pep8-naming
    "PERF", # perflint
    "RUF",  # ruff
    "UP",   # pyupgrade
    "W",    # pycodestyle warnings
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.isort]
force-single-line = true
lines-after-imports = 2

####################################################################################################
# MyPy
####################################################################################################

[tool.mypy]
exclude = ['maya_2023_install_files/*']
ignore_missing_imports = true
mypy_path = "$MYPY_CONFIG_FILE_DIR/src:$MYPY_CONFIG_FILE_DIR/tests"
namespace_packages = true
strict = true
warn_unused_ignores = false
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>
