### ISSUE TITLE
Extension provided snippets not available when extension installed from store

### ISSUE THREAD

**Issue by rapgenic** [zed-industries/zed#21774]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have recently published my [VHDL](https://github.com/rapgenic/zed-vhdl) extension, which contains extension provided snippets in the `snippets.json` file in the root of the extension, that are registered with `snippets = snippets.json` in the `extension.toml` file.

When the extension is installed from source, code completion shows them correctly. 

This is not the case now that I have installed it from the extension store.

Peeking the content of the `~/.local/share/zed/extensions/installed/vhdl` folder, I can see that no `snippets.json` file is present, and that the `extension.toml` file contains the following:

```toml
...
repository = "https://github.com/rapgenic/zed-vhdl"
authors = ["Giulio Girardi <giulio.girardi@protechgroup.it>"]
themes = []
languages = ["languages/vhdl"]
snippets = "/home/runner/work/extensions/extensions/extensions/vhdl/snippets.json"
```

Clearly the last `snippets = ...` line is pointing to a non existent location!

### Environment

Zed: v0.166.0 (Zed Nightly c5b6d78d5b01e0fcd243499bf3fb09cb1c758902)
OS: Linux Wayland fedora 41
Memory: 7.4 GiB
Architecture: x86_64
GPU: Intel(R) Xe Graphics (TGL GT2) || Intel open-source Mesa driver || Mesa 24.2.7
