### ISSUE TITLE
Delete Inactive Branches

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#22916]
### Check for existing issues

- [X] Completed

### Describe the feature

This feature adds an automated `GitHub Action` that runs weekly to delete inactive branches that have not been updated for the past `4 months`. This helps to keep the repository clean and free from outdated branches, ensuring better repository management.

```yaml
name: Delete Inactive Branches

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  delete-inactive-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get list of branches and their last update time
        run: |
          branches=$(git branch -r --format '%(refname:short)')
          DAYS_INACTIVE=120
          NOW=$(date +%s)
          CUTOFF=$((NOW - DAYS_INACTIVE * 86400))

          for branch in $branches; do
            last_commit_date=$(git log -1 --format=%ct origin/$branch)
            if [[ $last_commit_date -lt $CUTOFF && $branch != "origin/main" ]]; then
              echo "Deleting inactive branch: $branch (last commit: $last_commit_date)"
              git push origin --delete $branch
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Zed Version and System Specs

```
Zed: v0.168.2 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```
