### ISSUE TITLE
A particular type of Lefthook usage causes Terminal output to erase

### ISSUE THREAD

**Issue by silvenon** [zed-industries/zed#24026]
### Summary

When running a [Lefthook](https://lefthook.dev/) task that uses parallel jobs, this triggers the terminal output to erase. Commands work fine, and running jobs in sequence works fine. I initially reported this in evilmartians/lefthook#943, but considering that it works in Vercel's Hyper I don't think it's a Lefthook bug.

https://github.com/user-attachments/assets/6c6b64d6-d1f7-4cc8-91f8-31f401cf7f2b

Steps to trigger the problem:
1. install Lefthook: `npm install --save-dev lefthook`
2. configure a hook with parallel jobs, for example:
    ```yml
    pre-push:
      parallel: true
      jobs:
        - run: npx eslint .
        - run: npx prettier --check .
        - run: npx tsc --noEmit
        - run: npx vitest run
    ```
3. run the hook: `npx lefthook run pre-push --force`

Actual Behavior: basically summary remains as the only output, plus a big chunk of the existing terminal output gets erased.

Expected Behavior: Lefthoook provides a nice progress experience, showing output of all jobs running in parallel, along with the summary at the end. Seems like that progress experience has turned into a black hole for Zed's integrated terminal.

### Zed Version and System Specs

Zed: v0.171.4 (Zed)
OS: macOS 15.2.0
Memory: 16 GiB
Architecture: aarch64
