### ISSUE TITLE
Vim '%' matching bracket motion doesnt work inside comments and certain template languages

### ISSUE THREAD

**Issue by tannersltwtr** [zed-industries/zed#25435]
### Summary

Vim-mode's `%` bracket matching jump fails when inside commented code and fails on template languages like Shopify's Liquid `{% ... %}` or `{{ ... }}` brackets.

Steps to trigger the problem:
1. Find a piece of valid code where bracket matching works.
2. Comment the code out
3. Try jumping on the same bracket and notice it no longer works
4. For the template language issue, open a file ending in .liquid, notice bracket jumping works on HTML code/JS code but fails on template brackets

Actual Behavior:
Cursor doesnt move

Expected Behavior:
Cursor jumps to matching bracket

### Zed Version and System Specs

Zed: v0.174.6 (Zed) 
OS: macOS 15.3.1
Memory: 48 GiB
Architecture: aarch64

**Comment by EdoAPP** [comment]
Bumping this. This seems to be a bit inconsistent overall. I'm having the exact same problem in a css file using tailwind. As you can see in the video attached, sometimes it works, sometimes it doesn't. I can't tell what makes it fail.

https://github.com/user-attachments/assets/3463b3db-72ec-43b3-b6bd-cf7df1d13e83

Macos M1 pro, 32 gb ram.

**Comment by ConradIrwin** [comment]
For liquid and tailwind, we should be able to update the `brackets.scm` to work correctly.

Comments are currently plain-text, which we don't yet have % support for.

**Comment by EdoAPP** [comment]
@ConradIrwin I'm not familiar with the codebase or rust _at all_ but it seems that we have `brackets.scm` definition per language. `css` seems to already [support](https://github.com/zed-industries/zed/blob/0a2d938ac56a5dfb0845f9646fac0416c0aae8e5/crates/languages/src/css/brackets.scm#L3) `{ }` but that doesn't explain why sometimes it works and sometimes it doesn't. Perhaps needs additional digging?

**Comment by ConradIrwin** [comment]
are you able to share that file (either here, or privately to conrad@zed.dev – I won't use it except to try and reproduce this)

**Comment by EdoAPP** [comment]
> are you able to share that file (either here, or privately to [conrad@zed.dev](mailto:conrad@zed.dev) – I won't use it except to try and reproduce this)

@ConradIrwin here's a simplified version of it: (I removed a bunch of lines to keep it simpler but still showcase the problem)

Notice that doing '%' in the first bracket `@layer utilities {` dones't work but the next one do. Same issue with with `.ag-cell-focus` and all the following brackets.

Saved as a `.css` file using zed `0.176.2`
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer utilities {
  .popover-width-trigger {
    width: var(--radix-popover-trigger-width);
    max-height: var(--radix-popover-content-available-height);
  }

  .ag-theme-quartz {
    --ag-icon-font-family: agGridAlpine;
    --ag-font-family: theme("fontFamily.sans");

    /* borders */
    .ag-column-last {
      --ag-cell-horizontal-border: none;
    }

    .action-cell {
      /*4px including borders;*/
      @apply py-[3px];
      --ag-cell-horizontal-padding: 5px;
    }
    .ag-header {
      --ag-cell-horizontal-padding: 8px;
    }
    .ag-cell {
      @apply border-[0.5px];
    }

    .ag-cell-focus {
      @apply rounded-2 !border-thin !border-primary-hover ring-[1.5px] ring-inset ring-primary-hover;

      &.suppress-navigable {
        --ag-range-selection-border-color: none;
        --ag-input-focus-border-color: none;

        @apply !border-thin !border-transparent !border-r-default-color !ring-transparent focus-within:rounded-0;

        &.ag-column-first {
          @apply !border-l-[0px] !border-r-default-color;
        }

        &.ag-column-last {
          @apply !border-l-default-color;
          @apply !border-r-transparent;
        }

        &.filler-col {
          @apply !border-r-transparent;
        }
      }
    }
  }
}
```
