### ISSUE TITLE
Breaking YAML files containing multiple curly braces

### ISSUE THREAD

**Issue by sutonea** [zed-industries/zed#25536]
### Summary

There is an issue where saving a YAML file would result in line breaks being inserted into any nested curly braces in the file.

Steps to trigger the problem:
1. Open YAML file includes multi curly braces
2. Add a blank line to the end of the file
3. Save file
4. Show git diff

Actual Behavior:

![Image](https://github.com/user-attachments/assets/a4fe8b5b-9dbf-4b6f-9273-909681d10423)

Expected Behavior:

![Image](https://github.com/user-attachments/assets/47e8ed39-c5e6-4b53-bf60-03080dc5a7a4)

### Zed Version and System Specs

Zed: v0.174.6 (Zed) 
OS: macOS 14.7.4
Memory: 8 GiB
Architecture: x86_64

**Comment by sutonea** [comment]
Would it be sufficient to modify the following file?

https://github.com/zed-industries/zed/blob/cea06bc0ce6aabcd09789aaa4b0fb630423d89d6/crates/languages/src/yaml/config.toml#L7

**Comment by devzeth** [comment]
Hi, thank you for the report however I'm unable to reproduce it. 
As requested in the bug template, please provide us a a yml snippet to reproduce the issue. Furthermore do you have any language setting that would affect this? (wrapping, preferred line length etc).  

Thank you.

**Comment by sutonea** [comment]
Thank you. This is yml snippet.

before save:
---

```yml
sample:
  string_a: { { 1234567890123456789012345678901234567890123456789012345678901234567890 } }
  string_b: { { 123456789012345678901234567890123456789012345678901234567890 } }
  string_c: { { 12345678901234567890123456789012345678901234567890 } }
  string_d: { { 1234567890123456789012345678901234567890 } }
  string_e: { { 123456789012345678901234567890 } }
  string_f: { { 12345678901234567890 } }
  string_g: { { 1234567890 } }
```

after save:
----

```yml
sample:
  string_a:
    {
      {
        1234567890123456789012345678901234567890123456789012345678901234567890,
      },
    }
  string_b: { { 123456789012345678901234567890123456789012345678901234567890 } }
  string_c: { { 12345678901234567890123456789012345678901234567890 } }
  string_d: { { 1234567890123456789012345678901234567890 } }
  string_e: { { 123456789012345678901234567890 } }
  string_f: { { 12345678901234567890 } }
  string_g: { { 1234567890 } }

```

> Furthermore do you have any language setting that would affect this? (wrapping, preferred line length etc).

I have not set any particular settings.

Thank you.
