### ISSUE TITLE
License mismatch in reqwest_client crate

### ISSUE THREAD

**Issue by JosBritton** [zed-industries/zed#29527]
### Summary

In the `reqwest_client` crate, I noticed the package license field reads Apache-2.0 while the license file linked is GPLv3

```toml
[package]
name = "reqwest_client"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"
```

```
./crates/reqwest_client/LICENSE-GPL
```

### Description

Steps to reproduce:
n/a

Expected Behavior:
Actual Behavior:

### Zed Version and System Specs

n/a
