### ISSUE TITLE
Broken SCSS highlighting when after `:` with no space afterwards

### ISSUE THREAD

**Issue by panstromek** [zed-industries/zed#30506]
### Summary

If you omit space after `:` in CSS properties, the highlighting after that line is broken:

![Image](https://github.com/user-attachments/assets/adc9c1e8-1d36-41bd-8057-936495099316)

### Description

Steps to reproduce:
1. Paste this CSS into a new SCSS file:
```scss

a.skip-main {
    left:-999px;
    position:absolute;
    top:auto;
    width:1px;
    height:1px;
    overflow:hidden;
    z-index:-999;
}
```

Expected Behavior: correct highligting
Actual Behavior: highlighting broken, some highliting is mid word, most is just grey/purple

Notes:
 -  This works correctly in CSS files.
 -  If you add space after any `:` in the paragraph above, following highlighting is fixed until next `:` without space.

### Zed Version and System Specs

Zed: v0.185.15 (Zed) 
OS: Linux Wayland ubuntu 24.04
Memory: 30.7 GiB
Architecture: x86_64
GPU: AMD Radeon 780M (RADV GFX1103_R1) || radv || Mesa 24.2.8-1ubuntu1~24.04.1
