### ISSUE TITLE
Cannot parse `package` in dependencies in `Cargo.toml`

### ISSUE THREAD

**Issue by michalfita** [zed-industries/zed#32409]
### Summary

Looks like Zed cannot deal with perfectly valid _rename_ of dependencies using `package =` field.

### Description

Following declaration of dependencies in `Cargo.toml` is perfectly valid:
```toml
[dependencies]
embedded-hal-02 = { package = "embedded-hal", version = "0.2.7", features = ["unproven"] }
embedded-hal-1 = { package = "embedded-hal", version = "1.0" }
```

Steps to reproduce:
1. Add these two lines above to the `Cargo.toml`
2. Observe error message and red underscore of the first element before `=`
3. The error hint says "expected value at line 1 column 1"
4. `rust-analyzer` is not launched

**Expected Behavior**: No error here.
**Actual Behavior**: Error marked and problems elsewhere.

### Zed Version and System Specs

Zed: v0.189.5 (Zed) 
OS: Linux Wayland ubuntu 24.04
Memory: 27.2 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV REMBRANDT) || radv || Mesa 24.2.8-1ubuntu1~24.04.1
