### ISSUE TITLE
Inline colour previews don't correctly blend alpha values

### ISSUE THREAD

**Issue by afgomez** [zed-industries/zed#33505]
### Description
The inline colour preview box doesn't seem to blend the alpha value with the editor background.

This is how it looks like with the One Light theme

<img width="370" alt="Image" src="https://github.com/user-attachments/assets/ff0b9dc0-f2fa-4dec-9d1c-c116f4bd9b96" />

For comparison, this is how it shows in VSCode with the default light theme.

<img width="365" alt="Image" src="https://github.com/user-attachments/assets/545f77e2-8767-40c7-8f5e-994bc99c98e8" />

Steps to reproduce:
1. Set up a light theme
2. On a CSS file, add the following swatches
```css
body {
  background-color: rgba(255, 255, 255, 0);
  background-color: rgba(0, 0, 0, 0.5);
  background-color: rgba(255, 0, 0, 0.5);
}
```

**Expected Behavior**:
- Colours with `0` alpha should let the background show through.
- Colours with `0.5` alpha should properly blend with the background.

**Actual Behavior**:
- Colours with `0` alpha show black.
- Colours with `0.5` alpha show too dark.

### Zed Version and System Specs

Zed: v0.193.1 (Zed Preview) 
OS: macOS 15.5.0
Memory: 48 GiB
Architecture: aarch64
