### ISSUE TITLE
Auto-indent causes issues with YAML files

### ISSUE THREAD

**Issue by pat-s** [zed-industries/zed#9441]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

(Thanks for this editor! I was finally able to replace VSCode with it and save a ton of battery 😄 )

When copying a YAML code part from one YAML file to another one, the `auto-indent` feature automatically adjusts the indent (to the worse) and nests it below the parent key.

This is quite annoying as I'd expect a YAML block sitting in the root of the document to be indented in the same way in the other document when pasting it.
Especially when the block is larger, I have to adjust the indent for XX amount of lines.

I suspect that https://github.com/zed-industries/zed/pull/2035 is responsible for that but I might be wrong.
I haven't found a way to turn `auto-indent` off in any way.

### Environment

Zed: v0.126.2 (Zed)
OS: macOS 14.4.0
Memory: 32 GiB
Architecture: aarch64

**Comment by jeffcox** [comment]
This has driven me away from using Zed in the short term.


Copy and paste this entire block in Zed pane with YAML syntax, it works fine.
```yaml
list:
  - of
  - things

another:
  - list
```

Copy and paste each list separately and it will forcibly indent the second pasted list, resulting in this:
```yaml
list:
  - of
  - things
  another:
    - list
```

**Comment by d1y** [comment]
> This has driven me away from using Zed in the short term.
> 
> Copy and paste this entire block into a Zed pane with YAML syntax, it works fine.
> 
> ```yaml
> list:
>   - of
>   - things
> 
> another:
>   - list
> ```
> 
> Copy and paste each list separately and it will forcibly indent the second pasted list, resulting in this:
> 
> ```yaml
> list:
>   - of
>   - things
>   another:
>     - list
> ```

I also have this problem

**Comment by jeffcox** [comment]
I tried setting `"languages": {"YAML": {"enable_language_server": false } }` today while wondering about this bug, the issue persists.

**Comment by notpeter** [comment]
I think we may have pushed a fix for this today, can you download the preview release and verify if your issue is solved?

See also:
- https://github.com/zed-industries/zed/issues/13338
- https://github.com/zed-industries/zed/pull/13351

**Comment by azriel91** [comment]
Heya, I tried pasting the two lists on zed preview 0.141.2, and the issue is partially fixed.

Pasting the two lists individually when the caret is at column 1 (index 0) works nicely:

```yaml
list:
  - of
  - things

another:
  - list
```

But when pasting nested maps, where the caret is not on column 1, the inner maps are indented by the number of spaces before the caret:

```yaml
outer:
  inner1:
    - item

  # <- place caret at column 3 (two spaces)
```

paste in inner2, but don't select the leading two spaces:

```yaml
  inner2:
    - item
```

expected:

```yaml
outer:
  inner1:
    - item

  inner2:
    - item
```

actual:

```yaml
outer:
  inner1:
    - item

  inner2:
      - item
  # ^^ extra spaces
```

Notably it only happens when the second list is copied from outside Zed, so presumably there's extra context that tells zed whether what's being pasted has indentation. 

Arguably it could be "expected behaviour" since zed doesn't know if the externally copied text is *meant* to be indented with the additional spaces from the caret's position, but I think in YAML, it's more likely that it shouldn't.

**Comment by jeffcox** [comment]
I am still able to replicate this issue when pasting the lists directly below one another.  As I understand it while this is a bit of an eyesore, it is valid YAML:

```yaml
list_one:
  - one
  - two
list_two:
  - three
  - four
```

Trying to paste `list_two` directly below `list_one`, even after de-indenting back to column 0, results in the same undesirable behavior:

```yaml
list_one:
  - one
  - two
  list_two:
    - three
    - four
```

The partial fix is a HUGE improvement and I am excited to give Zed another try.

**Comment by kuglee** [comment]
I have the same issue with Roc files too. Pasting even when at column 0 makes the code indented:

```roc
func1 = \a ->
    "hello"

    func2 = \a ->
        "hello"

```

**Comment by notpeter** [comment]
The pasting auto-indent issue for YAML should be fixed by:
- https://github.com/zed-industries/zed/pull/20193
- which closed: https://github.com/zed-industries/zed/issues/13338

This issue appears to have been overlooked, but I wanted to give folks a heads up.

@jeffcox: I can no longer reproduce with the example you provided.
@azriel91 I can no longer reproduce with the example you provided.

@kuglee You should be able to disable this for Roc in your settings:
```json
  "languages":
    "Roc": {
      "auto_indent_on_paste": false
    }
  }
```

If you still have test-cases where formatting is being handled poorly in in current Zed Stable/Preview, please open a clean issue.

This was a PITA and the worst of it seems to be fixed.
Thanks all for reporting!

**Comment by dimitre** [comment]
sometimes, in some circunstances ZED is auto identing YAML with tabs, or 4 spaces as soon as I save it.
usually to preserve the file I have 
to ctrl-Z, 
copy to clipboard. 
reopen ZED
and save again.
it seems to work now.
I'll investigate better how to reproduce this.

here is a problematic one (not sure if has to do with the file itself)
```yaml
name: ofgen
version: 0.1.1
abstracts:*:
  language: C++
  # language[toolchain:apple-llvm]: Objective-C++
  settings:Cxx:
    cppStandard: c++20
    warningsPreset: minimal
    runtimeTypeInformation: true
    threads: true
    exceptions: true
targets:
  ofgen:
    kind: executable
    settings:Cxx:
      includeDirs:
        - src
        - src/uuidxx/src
      includeDirs[:windows]:
        - ../libs/vs/include/
      includeDirs[:macos]:
        - ../libs/macos/include/
      includeDirs[:linux]:
        - ../libs/linux64/include/
      defines:
        # - YAML_CPP_NO_DLL
        - YAML_CPP_STATIC_DEFINE
      staticLinks[:windows]:
        - ../libs/vs/lib/pugixml.lib
        - ../libs/vs/lib/yaml-cpp.lib
      staticLinks[:macos]:
        - ../libs/macos/lib/libpugixml.a
        - ../libs/macos/lib/libyaml-cpp.a
      staticLinks[:linux]:
        - ../libs/linux64/lib/libpugixml.a
        - ../libs/linux64/lib/libyaml-cpp.a

    files:
      include:
        - src/*.cpp
        - src/uuidxx/src/*.cpp
      exclude:
        - cmake
        - .zed
distribution:
  ofgen:
    kind: executable
    files:
      - ${externalBuild:ofgen}

```
